version: 0.2

phases:
  build:
    commands:
      - . scripts/deploy.sh
      - sam package --template-file template.yaml --s3-bucket photosearch-lambda-code-pipeline --output-template-file packaged.yaml
artifacts:
  files:
    - "packaged.yaml"
  discard-paths: yes